### ISSUE TITLE
Home responsive bug

### ISSUE THREAD

**Issue by Nidev-lab** [Nidev-lab/perito-siniestros#29]
In mobile version.

![image](https://user-images.githubusercontent.com/53904695/161448544-f19500b2-53b5-4f00-8082-1fa29390a3ab.png)
![image](https://user-images.githubusercontent.com/53904695/161448553-0e9752d1-c680-4776-a2fe-13c49b70c012.png)

**Comment by cajimenez96** [comment]
Resolved
